version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - netRudi

  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: rudineybarbosa/node-express
    container_name: node
    ports:
      - "3000:3000" 
    volumes:
    - ./node:/usr/src/app
    - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db
    entrypoint: node index.js
    networks:
      - netRudi

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: rudineybarbosa/nginx-rudi
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - netRudi      

networks:
  netRudi:
    name: netRudi
    driver: bridge